### ISSUE TITLE
Adicionar favicon

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/OpenDevUFCG#18]
Colocar no favicon logo da organização

**Comment by JuanBarros2** [comment]
Foi adicionado um, mas ele ta estourado. Já estou arrumando isso :+1:

**Comment by JuanBarros2** [comment]
![image](https://user-images.githubusercontent.com/11728655/53674195-f9ffc680-3c6a-11e9-9f58-cc6a0835a400.png)
Assim fica melhor?

**Comment by JuanBarros2** [comment]
@thayannevls, ou o azul que já estava fica bom?

**Comment by thayannevls** [comment]
Nem tá aparecendo no meu navegador o ícone, já tentei guia anônima e tudo mas nada. Mas enfim, ficou melhor mesmo

Tem alguma razão pra escolher essa que é escura? E essa clara?
![favicon](https://user-images.githubusercontent.com/6867958/53674812-595fd580-3c6f-11e9-963b-9e656e5ee543.png)

**Comment by JuanBarros2** [comment]
Acho que esse azul lembra muito o twitter ó 
![image](https://user-images.githubusercontent.com/11728655/53674868-f458af80-3c6f-11e9-821e-0ca89cf71b25.png)

**Comment by thayannevls** [comment]
É verdade, então ficou bom o que tu disse. Coloca.
