### ISSUE TITLE
Sugestão de design para tela de introdução

### ISSUE THREAD

**Issue by danielmitre** [OpenDevUFCG/OpenDevUFCG#39]
## Sugestão de incremento para #31

Mudar a animação atual, no texto `desenvolvendo [com/para] a comunidade` para algo no estilo `desenvolvendo para [a comunidade/a UFCG/os estudantes/você]`.

O vue tem uma coleção interessante de transição com vários hooks pra adicionar animações. Uma ideia de animação já sugerida no gitter foi essa: https://greensock.com/forums/topic/11361-typewriter-effect/

**EDIT**: Já linkaram uma versão vue da animação (galera do gitter é top, não fique de fora) https://cngu.github.io/vue-typer/

**Comment by FannyVieira** [comment]
Que bacana, gostei!

**Comment by JuanBarros2** [comment]
Implementando! Obrigado @danielmitre :heart:
