### ISSUE TITLE
Meu nome tá errado >:(

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/OpenDevUFCG#41]
Meu nome tá José Rean :angry: KKKKKK 

https://github.com/OpenDevUFCG/OpenDevUFCG/blob/2c44a31b43fdedae347702801f2f035de96062fb/components/home/sessoes/equipe/Equipe.vue#L42

**Comment by danielmitre** [comment]
Eu acho que coisas como essa podem esperar passar a semana do fera, em prol de issues mais importantes e urgentes.

###### Se você tirar dúvida sem ser de react eu mudo de ideia e ainda ajeito a ordem alfabética

**Comment by JRobsonJr** [comment]
KKKKKKKKKKKKKKKKKKKKKKKK

**Comment by danielmitre** [comment]
Please close
