### ISSUE TITLE
Refatorar card de contribuição

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/OpenDevUFCG#50]
Creio que os cards em "faça sua contribuição" deveriam estar com um design um pouco diferente:

* Ao invés de deixar um retângulo vazio de outra cor, seria interessante adicionar alguma imagem de referência ao github e ao gitter, maybe o octocat e o ícone do gitter
* Ao invés de adicionar um link "Acessar ->" no canto inferior direito do componente, creio que valha mais a pena colocar uma ação de click no card em si, ou na imagem/título/descrição do card

**Comment by LukeHxH** [comment]
O retângulo vazio é para as imagens que @hericlesme está fazendo

**Comment by LukeHxH** [comment]
Quanto à segunda sugestão, pode ser uma ótima mesmo, começarei a fazer isso.
