### ISSUE TITLE
Adicionar espaçamento na ultima sessão

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/OpenDevUFCG#62]
Seria legal colocar um espaçamento inferior na ultima sessão, pois fica meio estranho do jeito que tá.

**Comment by LukeHxH** [comment]
Eu coloco já na PR que ajeita o link do Discord?

**Comment by JuanBarros2** [comment]
Pode ser. Aí comenta "fix #id dessa issue"
