### ISSUE TITLE
Decidir que páginas vamos ter

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/OpenDevUFCG#7]
Que páginas vamos ter no site? Penso em ter as seguintes:

- Página principal: Uma landing page de apresentação pra nossa organização
- Time: Uma página mostrando nosso time principal
- Projetos/Colmeias: Uma página mostrando nossos projetos e que possa redirecionar pra eles. Se ficar pequeno, pode colocar na página principal mesmo.

**Comment by JuanBarros2** [comment]
Acho que no mínimo esses temas seriam necessários
