### ISSUE TITLE
Melhorar responsividade de seções

### ISSUE THREAD

**Issue by pedroespindula** [OpenDevUFCG/OpenDevUFCG#70]
**Descrição da melhoria:**
Melhorar responsividade para seções de "Visão" e "Sobre nós".

**Necessidade da melhoria:**
Existe espaço que não é preenchido e com isso, parece que algo está para ser carregado.

**Como ela pode ser implementada:**
Usando css grid e flex em conjunto com propriedades de alinhamento.

**Imagens:**
![Screenshot from 2019-07-17 19-48-16](https://user-images.githubusercontent.com/38431219/61416984-090aac80-a8cc-11e9-8c2c-73881a79e516.png)
![Screenshot from 2019-07-17 19-48-26](https://user-images.githubusercontent.com/38431219/61416989-0a3bd980-a8cc-11e9-8320-c3e838f737cd.png)

**Comment by thayannevls** [comment]
Vou tentar resolver enquanto to reescrevendo algumas coisas

**Comment by thayannevls** [comment]
@pedroespindula Diz a resolução dessa tela por favor

**Comment by pedroespindula** [comment]
> @pedroespindula Diz a resolução dessa tela por favor

Os itens da de visao poderiam ficar mais distantes do centro e os de sobre nos poderiam alinhar com o centro.

**Comment by thayannevls** [comment]
@pedroespindula ?? O tamanho da tua tela kkk

**Comment by pedroespindula** [comment]
> @pedroespindula ?? O tamanho da tua tela kkk Olha no browser, só pra eu testar aqui

AAAAAAAAAAAAAAAAAAA pensei que era resolução no sentido de resolver kkkkkkkkkkkk.

Resolução: 2560 x 1080

**Comment by thayannevls** [comment]
kkkkkkkkkkkk vlww

**Comment by thayannevls** [comment]
@pedroespindula pode testar novamente por favor?

**Comment by pedroespindula** [comment]
Qual a branch @thayannevls ?

**Comment by thayannevls** [comment]
Vou abrir issue, valeu @pedroespindula
